name: Daily DJinni Parser

on:
  schedule:
    - cron: '10 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install selenium openpyxl tqdm

      - name: Run parser
        run: python mainpars.py

      - name: Publish Excel to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"

          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

          git rm -rf .
          copy djinni_structured_tqdm.xlsx .
          git add djinni_structured_tqdm.xlsx
          git commit -m "Daily update: ${{ github.run_date }}"
          git push origin gh-pages --force