name: Daily DJinni Parser
permissions:
  contents: write
  pages: write

on:
  schedule:
    - cron: '*/30 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install selenium openpyxl tqdm

      - name: Run parser
        run: python HR11/mainpars.py
      
      - name: Commit Excel to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add djinni_structured_tqdm.xlsx
          git commit -m "Update Excel for ${{ github.run_date }}" || echo "No changes to commit"
          git push origin main

      - name: Publish Excel to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"

          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

          # Спочатку переіменуємо щойно згенерований файл у тимчасовий
          mv djinni_structured_tqdm.xlsx tmp.xlsx
          # Видаляємо все в гілці gh-pages
          git rm -rf .
          # Повертаємо наш Excel із tmp.xlsx
          mv tmp.xlsx djinni_structured_tqdm.xlsx
          git add djinni_structured_tqdm.xlsx
          git commit -m "Daily update: ${{ github.run_date }}"
          git push origin gh-pages --force
